package srl.neotech.aeroporto;

public enum StatoAereo {
	//stato (Enumeration: IN_PARTENZA,DECOLLATO,FUORI_SPAZIO_AEREO,IN_AVVICINAMENTO,ATTERRATO).
	IN_PARTENZA,
	DECOLLATO,
	FUORI_SPAZIO_AEREO,
	IN_AVVICINAMENTO,
	ATTERRATO
}